# Generated by Django 5.0.3 on 2024-03-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(default='', max_length=30)),
                ('file_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=30)),
                ('file_name', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
    ]
