# Generated by Django 5.0.3 on 2024-03-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='file_name',
        ),
    ]
