# Generated by Django 5.0.3 on 2024-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_subcategory_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
