# Generated by Django 5.0.3 on 2024-04-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_subcategory_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='file_name',
        ),
    ]
