# Generated by Django 5.0.3 on 2024-03-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('smalldescription', models.TextField()),
                ('largedescription', models.TextField()),
                ('setupprice', models.CharField(max_length=50)),
                ('setupduration', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=50)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.category')),
                ('subcategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.subcategory')),
            ],
            options={
                'db_table': 'idea',
            },
        ),
    ]
