# Generated by Django 5.0.3 on 2024-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovators', '0002_idea_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='file',
        ),
        migrations.AddField(
            model_name='idea',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
