# Generated by Django 5.0.3 on 2024-04-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovators', '0003_remove_idea_file_idea_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='file_name1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
