# Generated by Django 5.0.3 on 2024-03-26 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='', max_length=30)),
                ('comment', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
    ]
