# Generated by Django 5.0.3 on 2024-04-01 13:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessperson', '0003_profile_role'),
        ('innovators', '0003_remove_idea_file_idea_file_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='completed', max_length=100)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='innovators.idea')),
                ('innovator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='businessperson.profile')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
