# Generated by Django 5.0.3 on 2024-04-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessperson', '0005_alter_order_innovator_alter_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
