# Generated by Django 5.0.3 on 2024-04-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessperson', '0007_remove_profile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
