# Generated by Django 5.0.3 on 2024-04-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessperson', '0013_alter_feedback_user'),
        ('innovators', '0004_idea_file_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovators.idea'),
        ),
    ]
